<?php

/**
 * Implements hook_libraries_info().
 *
 * For defining external libraries.
 */
function chelsea_analysis_libraries_info() {
  // A very simple library. No changing APIs (hence, no versions), no variants.
  // Expected to be extracted into 'sites/all/libraries/phpexcel'.
  $libraries['phpexcel'] = array(
    'name' => 'PHPExcel library',
    'vendor url' => 'https://phpexcel.codeplex.com/',
    'download url' => 'https://phpexcel.codeplex.com/releases/view/119187',
    'version callback' => 'phpexcel_version_callback',
    'files' => array(
      'php' => array('Classes/PHPExcel.php'), //this can be a path to the file location like array('lib/simple.js')
    ),
  );
  return $libraries;
}

function phpexcel_version_callback(){
   return TRUE;
}

function chelsea_analysis_menu() {
  $items['admin/chelsea-analysis'] = array(
    'title' => t('Chelsea Analysis'),
    'page callback' => 'chelsea_analysis_page',
    'access arguments' => array('administer chelsea_analysis'),
	'access callback' => TRUE,
  );
  return $items;
}

function chelsea_analysis_page_alter(&$page){
//dpm($page);
}


function chelsea_analysis_requirements($phase) {
  $requirements = array();
  $t = get_t();
  $requirements['chelsea_analysis'] = array(
    'title' => $t('PHPExcel Library'),
  );
  $libraries = libraries_get_libraries();
  if (isset($libraries['PHPExcel'])) {
    $requirements['PHPExcel']['value'] = $t('Installed');
    $requirements['PHPExcel']['severity'] = REQUIREMENT_OK;
  }
  else {
    $requirements['PHPExcel']['value'] = $t('Not Installed');
    $requirements['PHPExcel']['severity'] = REQUIREMENT_ERROR;
    $requirements['PHPExcel']['description'] = $t('Please install the PHPExcel library %url.', array('%url' => 'http://phpexcel.codeplex.com/'));
  }

  return $requirements;
}

function chelsea_analysis_contents($nid){
	dpm($nid);
  mysql_connect('localhost', 'servilla_alpha', 'grupoly2014');
  mysql_select_db('servilla_encuestas2');
  $consulta = sprintf("SELECT nid, sid, serial, submitted, remote_addr FROM webform_submissions WHERE nid = '%s' ORDER BY submitted DESC LIMIT 0,999999999", mysql_real_escape_string($nid));
  $query = mysql_query($consulta);
  $v5 = 0;$data = array();$v1 = 0;$v3 = 0;
  while($v7 = mysql_fetch_assoc($query)) {
  		foreach($v7 as $key => $value) {
  				$data['submissions'][$v5][$key] = $value;
  			}
		$v5 += 1;
	}

  foreach ($data['submissions'] as $rows) {
  	$consulta2 = sprintf("SELECT sid, cid, no, data FROM  webform_submitted_data WHERE sid = '%s' LIMIT 0,999999999", mysql_real_escape_string($rows['sid']));
	/*$new_query = mysql_query("select sid, cid, no, data from webform_submitted_data where sid='".$rows['sid']."' limit 0,999999999");*/
	$new_query = mysql_query($consulta2);
	while($v2 = mysql_fetch_assoc($new_query)){
	  foreach($v2 as $key => $value){
	    $data['submitted_data'][$v1][$v3][$key] = $value;
	  }
	  $v3 += 1;
	}
	$v1 += 1;
  }
  return $data;
}

function chelsea_analysis_page() {       
    $page = "";
	if (user_access('access content')) {
	  $result = chelsea_analysis_contents(1);
	  $submissions = count($result['submissions']);
	  $si_no = array();
	  dpm($submissions);
	  foreach ($result['submitted_data'] as $submission) {
	    foreach($submission as $rows){
		  if ($rows['data'] == 'si'){
		    if ($rows['cid'] == 16) { ++$si_no['q1si']; }
			if ($rows['cid'] == 19) { ++$si_no['q2asi']; }
			if ($rows['cid'] == 22) { ++$si_no['q2bsi']; }
			if ($rows['cid'] == 25) { ++$si_no['q2csi']; }
			if ($rows['cid'] == 28) { ++$si_no['q2dsi']; }
			if ($rows['cid'] == 31) { ++$si_no['q2esi']; }
			if ($rows['cid'] == 34) { ++$si_no['q2fsi']; }
			if ($rows['cid'] == 37) { ++$si_no['q2gsi']; }
			if ($rows['cid'] == 40) { ++$si_no['q2hsi']; }
			if ($rows['cid'] == 43) { ++$si_no['q2isi']; }
			
		  }
		  if ($rows['data'] == 'alta'){
		    ++$si_no['q3alta'];
		  }
		  if ($rows['data'] == 'media'){
		    ++$si_no['q3media'];
		  }
		  if ($rows['data'] == 'baja'){
		    ++$si_no['q3baja'];
		  }
		  if ($rows['data'] == 'ninguna'){
		    ++$si_no['q3ninguna'];
		  }
		  if ($rows['data'] == 'no'){
		    if ($rows['cid'] == 16) { ++$si_no['q1no']; }
			if ($rows['cid'] == 19) { ++$si_no['q2ano']; }
			if ($rows['cid'] == 22) { ++$si_no['q2bno']; }
			if ($rows['cid'] == 25) { ++$si_no['q2cno']; }
			if ($rows['cid'] == 28) { ++$si_no['q2dno']; }
			if ($rows['cid'] == 31) { ++$si_no['q2eno']; }
			if ($rows['cid'] == 34) { ++$si_no['q2fno']; }
			if ($rows['cid'] == 37) { ++$si_no['q2gno']; }
			if ($rows['cid'] == 40) { ++$si_no['q2hno']; }
			if ($rows['cid'] == 43) { ++$si_no['q2ino']; }
			
		  }
		  if (empty($rows['data']) || is_null($rows['data'])){
		    if ($rows['cid'] == 16) { ++$si_no['q1null']; }
			if ($rows['cid'] == 19) { ++$si_no['q2anull']; }
			if ($rows['cid'] == 22) { ++$si_no['q2bnull']; }
			if ($rows['cid'] == 25) { ++$si_no['q2cnull']; }
			if ($rows['cid'] == 28) { ++$si_no['q2dnull']; }
			if ($rows['cid'] == 31) { ++$si_no['q2enull']; }
			if ($rows['cid'] == 34) { ++$si_no['q2fnull']; }
			if ($rows['cid'] == 37) { ++$si_no['q2gnull']; }
			if ($rows['cid'] == 40) { ++$si_no['q2hnull']; }
			if ($rows['cid'] == 43) { ++$si_no['q2inull']; }
		}

		if($rows['data'] == '1'){ 
		  	if($rows['cid'] == 96) { ++$si_no['q4a1'];}
		  	if($rows['cid'] == 98) {++$si_no['q4b1'];}
		  	if($rows['cid'] == 100) {++$si_no['q4c1'];}
		  	if($rows['cid'] == 102) {++$si_no['q4d1'];}
		  	if($rows['cid'] == 104) {++$si_no['q4e1'];}
		  	if($rows['cid'] == 106) {++$si_no['q4f1'];}
		  	if($rows['cid'] == 108) {++$si_no['q4g1'];}
		  	if($rows['cid'] == 110) {++$si_no['q4h1'];}
		  	if($rows['cid'] == 112) {++$si_no['q4i1'];}
		  	if($rows['cid'] == 114) {++$si_no['q4j1'];}
		  	if($rows['cid'] == 116) {++$si_no['q4k1'];}
		  	if($rows['cid'] == 118) {++$si_no['q4l1'];}
		  	if($rows['cid'] == 120) {++$si_no['q4m1'];}
		  	if($rows['cid'] == 122) {++$si_no['q4n1'];}
		 }

		if($rows['data'] == '2'){ 
		  	if($rows['cid'] == 96) { ++$si_no['q4a2'];}
		  	if($rows['cid'] == 98) {++$si_no['q4b2'];}
		  	if($rows['cid'] == 100) {++$si_no['q4c2'];}
		  	if($rows['cid'] == 102) {++$si_no['q4d2'];}
		  	if($rows['cid'] == 104) {++$si_no['q4e2'];}
		  	if($rows['cid'] == 106) {++$si_no['q4f2'];}
		  	if($rows['cid'] == 108) {++$si_no['q4g2'];}
		  	if($rows['cid'] == 110) {++$si_no['q4h2'];}
		  	if($rows['cid'] == 112) {++$si_no['q4i2'];}
		  	if($rows['cid'] == 114) {++$si_no['q4j2'];}
		  	if($rows['cid'] == 116) {++$si_no['q4k2'];}
		  	if($rows['cid'] == 118) {++$si_no['q4l2'];}
		  	if($rows['cid'] == 120) {++$si_no['q4m2'];}
		  	if($rows['cid'] == 122) {++$si_no['q4n2'];}
		}

		if($rows['data'] == '3'){ 
		  	if($rows['cid'] == 96) { ++$si_no['q4a3'];}
		  	if($rows['cid'] == 98) {++$si_no['q4b3'];}
		  	if($rows['cid'] == 100) {++$si_no['q4c3'];}
		  	if($rows['cid'] == 102) {++$si_no['q4d3'];}
		  	if($rows['cid'] == 104) {++$si_no['q4e3'];}
		  	if($rows['cid'] == 106) {++$si_no['q4f3'];}
		  	if($rows['cid'] == 108) {++$si_no['q4g3'];}
		  	if($rows['cid'] == 110) {++$si_no['q4h3'];}
		  	if($rows['cid'] == 112) {++$si_no['q4i3'];}
		  	if($rows['cid'] == 114) {++$si_no['q4j3'];}
		  	if($rows['cid'] == 116) {++$si_no['q4k3'];}
		  	if($rows['cid'] == 118) {++$si_no['q4l3'];}
		  	if($rows['cid'] == 120) {++$si_no['q4m3'];}
		  	if($rows['cid'] == 122) {++$si_no['q4n3'];}
		}

		if($rows['data'] == '4'){ 
		  	if($rows['cid'] == 96) { ++$si_no['q4a4'];}
		  	if($rows['cid'] == 98) {++$si_no['q4b4'];}
		  	if($rows['cid'] == 100) {++$si_no['q4c4'];}
		  	if($rows['cid'] == 102) {++$si_no['q4d4'];}
		  	if($rows['cid'] == 104) {++$si_no['q4e4'];}
		  	if($rows['cid'] == 106) {++$si_no['q4f4'];}
		  	if($rows['cid'] == 108) {++$si_no['q4g4'];}
		  	if($rows['cid'] == 110) {++$si_no['q4h4'];}
		  	if($rows['cid'] == 112) {++$si_no['q4i4'];}
		  	if($rows['cid'] == 114) {++$si_no['q4j4'];}
		  	if($rows['cid'] == 116) {++$si_no['q4k4'];}
		  	if($rows['cid'] == 118) {++$si_no['q4l4'];}
		  	if($rows['cid'] == 120) {++$si_no['q4m4'];}
		  	if($rows['cid'] == 122) {++$si_no['q4n4'];}
		}

		if($rows['data'] == '5'){ 
		  	if($rows['cid'] == 96) { ++$si_no['q4a5'];}
		  	if($rows['cid'] == 98) {++$si_no['q4b5'];}
		  	if($rows['cid'] == 100) {++$si_no['q4c5'];}
		  	if($rows['cid'] == 102) {++$si_no['q4d5'];}
		  	if($rows['cid'] == 104) {++$si_no['q4e5'];}
		  	if($rows['cid'] == 106) {++$si_no['q4f5'];}
		  	if($rows['cid'] == 108) {++$si_no['q4g5'];}
		  	if($rows['cid'] == 110) {++$si_no['q4h5'];}
		  	if($rows['cid'] == 112) {++$si_no['q4i5'];}
		  	if($rows['cid'] == 114) {++$si_no['q4j5'];}
		  	if($rows['cid'] == 116) {++$si_no['q4k5'];}
		  	if($rows['cid'] == 118) {++$si_no['q4l5'];}
		  	if($rows['cid'] == 120) {++$si_no['q4m5'];}
		  	if($rows['cid'] == 122) {++$si_no['q4n5'];}
		}

		}
	  }
	$rand = 'test';
  	$filename = $rand.'.xls';
  	$page = '<div><a href="/sites/default/files/'.$filename.'">Download Excel Report</a></div>';

  	include_once(drupal_get_path('module','chelsea_analysis').'/phpexcel.inc');
	$data = array();

  	$headers = array(
  		array("","","" ),

  		array("","","","","","",""),

  		array("","",""));

  	$result = 
array(
  		array(
  			array("Q1 ¿Ha desarrollado el Programa de XXXXXX proyectos de extensión (pasantías, prácticas empresariales, charlas) en su Institución a través de sus estudiantes y profesores?","ANÁLISIS PARA CADA RESPUESTA","" ),
  			array("","COUNT","HI"), // Cabeceras de la pregunta 1
  			array(
  				"Si",
  				$si_no["q1si"],
  				(($si_no['q1si'] / $submissions))),
  			array(
  				"No",
  				$si_no["q1no"],
  				(($si_no['q1no'] / $submissions))),
  			array("No responde",
  				$si_no["q1null"]),
  			(($si_no['q1null'] / $submissions)),
  			array(), array(), array(), // Espacio para imprimir la pregunta 2

  			array("Q2 CALIFIQUE, SEGÚN EL CUADRO QUE APARECE A CONTINUACIÓN, EL IMPACTO SOCIAL QUE HAN TENIDO EN SU EMPRESA, ENTIDAD O INSTITUCIÓN EDUCATIVA LOS PROYECTOS DE EXTENSIÓN (PASANTÍAS, PRÁCTICAS EMPRESARIALES, PRÁCTICAS DOCENTES, CAPACITACIONES, ETC.) DESARROLLADO","ANÁLISIS PARA CADA SUB PREGUNTA","","","","",""),
  			array("","Si","","NO","","NO RESPONDE",""), // cabeceras de la pregunta 2
  			array("","FI","HI","FI","HI","FI","HI"),
  			array("Q2a Aplicación de nuevos procesos técnicos, tecnológicos, productivos, pedagógicos, , culturales, sociales, etc.",
  				$si_no['q2asi'], // FI
  				(($si_no['q2asi'] / $submissions)), // HI
  				$si_no['q2ano'], // FI
  				(($si_no['q2ano'] / $submissions)), // HI
  				$si_no['q2anull'], // FI
  				(($si_no['q2anull'] / $submissions))), // HI
  			array(
  				"Q2b Generación de nuevos proyectos pedagógicos ambientales o educativos.",
  				$si_no['q2bsi'],
  				(($si_no['q2bsi'] / $submissions)),
  				$si_no['q2bno'],
  				(($si_no['q2bno'] / $submissions)),
  				$si_no['q2bnull'],(($si_no['q2bnull'] / $submissions))),
  			array("Q2c Implementación de nuevos procedimientos, métodos científicos o pedagógicos.",
  				$si_no['q2csi'],
  				(($si_no['q2csi'] / $submissions)),
  				$si_no['q2cno'],
  				(($si_no['q2cno'] / $submissions)),
  				$si_no['q2cnull'],
  				(($si_no['q2cnull'] / $submissions))),
  			array("Q2d Aportes específicos a los procesos didácticos, ambientales, educativos, sociales, investigativos, tecnológicos, científicos, de reconstrucción social y cultural.",
  				$si_no['q2dsi'],
  				(($si_no['q2dsi'] / $submissions)),
  				$si_no['q2dno'],
  				(($si_no['q2dno'] / $submissions)),
  				$si_no['q2dnull'],
  				(($si_no['q2dnull'] / $submissions))),
  			array("Q2e Contribución a la interacción de la Institución con su comunidad educativa.",
  				$si_no['q2esi'],
  				(($si_no['q2esi'] / $submissions)),
  				$si_no['q2eno'],
  				(($si_no['q2eno'] / $submissions)),
  				$si_no['q2enull'],
  				(($si_no['q2enull'] / $submissions))),
  			array("Q2f Aportes a los planes y proyección en seguridad alimentaria y gestión de riesgo.",
  				$si_no['q2fsi'],
  				(($si_no['q2fsi'] / $submissions)),
  				$si_no['q2fno'],
  				(($si_no['q2fno'] / $submissions)),
  				$si_no['q2fnull'],
  				(($si_no['q2fnull'] / $submissions))),
  			array("Q2g Programas de formación continuada",
  				$si_no['q2gsi'],
  				(($si_no['q2gsi'] / $submissions)),
  				$si_no['q2gno'],
  				(($si_no['q2gno'] / $submissions)),
  				$si_no['q2gnull'],
  				(($si_no['q2gnull'] / $submissions))),
  			array("Q2h Oferta de servicios técnicos, consultas, asesorías, pruebas y ensayos",
  				$si_no['q2hsi'],
  				(($si_no['q2hsi'] / $submissions)),
  				$si_no['q2hno'],
  				(($si_no['q2hno'] / $submissions)),
  				$si_no['q2hnull'],
  				(($si_no['q2hnull'] / $submissions))),
  			array("Q2i Ejecución de políticas públicas",
  				$si_no['q2isi'],
  				(($si_no['q2isi'] / $submissions)),
  				$si_no['q2ino'],
  				(($si_no['q2ino'] / $submissions)),
  				$si_no['q2inull'],
  				(($si_no['q2inull'] / $submissions))),
  			array(), array(), array(), // Espacio para imprimir la pregunta 5
  			

  			array("Q3 CÓMO PERCIBE LA RELACIÓN ENTRE EL PERFIL PROFESIONAL DE LOS EGRESADOS DEL PROGRAMA DE XXXXXX Y SUS POSIBILIDADES DE DESEMPEÑO EN LA INSTITUCIÓN O EMPRESA","ANÁLISIS PARA CADA RESPUESTA",""),
  			array("","FI","HI"),
				array("Alta",
					$si_no["q3alta"],
						(
							($si_no['q3alta'] / $submissions)
						)
					),
				array("media",
					$si_no["q3media"],
					(($si_no['q3media'] / $submissions))),
				array("baja",
					$si_no["q3baja"],
					(($si_no['q3baja'] / $submissions))),
				array("ninguna",
					$si_no["q3ninguna"],
					(($si_no['q3ninguna'] / $submissions))
					),

			array(), array(), array(), // Espacio para imprimir la pregunta 4
			array("Q4 CALIFIQUE DE 1 A 5 (1- DEFICIENTE, 5- SUFICIENTE) LAS SIGUIENTES CARACTERÍSTICAS OBSERVADAS POR USTED, Y RELACIONADAS CON EL DESEMPEÑO DEL EGRESADO DE XXXXXX DE LA UNIVERSIDAD DEL QUINDÍO","ANÁLISIS PARA CADA RESPUESTA","","","","","","","",""),
			array("","1","","2","","3","","4","","5"), // cabeceras de la pregunta 4
			array("","FI","HI","FI","HI","FI","HI","FI","HI","FI","HI"), 
				array("Q4a Capacidad de integración de nuevas tecnologías y aplicación en su profesión",
					$si_no['q4a1'], // FI de q4a1
					($si_no['q4a1'] / $submissions), // HI de q4a1
					$si_no['q4a2'],
					($si_no['q4a2'] / $submissions),
					$si_no['q4a3'],
					($si_no['q4a3'] / $submissions),
					$si_no['q4a4'],
					($si_no['q4a4'] / $submissions),
					$si_no['q4a5'],
					($si_no['q4a5'] / $submissions),
					),
				array("Q4b Comportamiento ético",
					$si_no['q4b1'], // FI de q4b1
					($si_no['q4b1'] / $submissions), // HI de q4b1
					$si_no['q4b2'],
					($si_no['q4b2'] / $submissions),
					$si_no['q4b3'],
					($si_no['q4b3'] / $submissions),
					$si_no['q4b4'],
					($si_no['q4b4'] / $submissions),
					$si_no['q4b5'],
					($si_no['q4b5'] / $submissions),
					),
				array("Q4c Habilidades para identificar, definir y solucionar problemas",
					$si_no['q4c1'], // FI de q4c1
					($si_no['q4c1'] / $submissions), // HI de q4c1
					$si_no['q4c2'],
					($si_no['q4c2'] / $submissions),
					$si_no['q4c3'],
					($si_no['q4c3'] / $submissions),
					$si_no['q4c4'],
					($si_no['q4c4'] / $submissions),
					$si_no['q4c5'],
					($si_no['q4c5'] / $submissions),
					),
				array("Q4d Fundamentación básica – disciplinar",
					$si_no['q4d1'], // FI de q4d1
					($si_no['q4d1'] / $submissions), // HI de q4d1
					$si_no['q4d2'],
					($si_no['q4d2'] / $submissions),
					$si_no['q4d3'],
					($si_no['q4d3'] / $submissions),
					$si_no['q4d4'],
					($si_no['q4d4'] / $submissions),
					$si_no['q4d5'],
					($si_no['q4d5'] / $submissions),
					),
				array("Q4e Formación socio-humanística",
					$si_no['q4e1'], // FI de q4e1
					($si_no['q4e1'] / $submissions), // HI de q4e1
					$si_no['q4e2'],
					($si_no['q4e2'] / $submissions),
					$si_no['q4e3'],
					($si_no['q4e3'] / $submissions),
					$si_no['q4e4'],
					($si_no['q4e4'] / $submissions),
					$si_no['q4e5'],
					($si_no['q4e5'] / $submissions),
					),
				array("Q4f Habilidades de comunicación oral y escrita",
					$si_no['q4f1'], // FI de q4f1
					($si_no['q4f1'] / $submissions), // HI de q4f1
					$si_no['q4f2'],
					($si_no['q4f2'] / $submissions),
					$si_no['q4f3'],
					($si_no['q4f3'] / $submissions),
					$si_no['q4f4'],
					($si_no['q4f4'] / $submissions),
					$si_no['q4f5'],
					($si_no['q4f5'] / $submissions),
					),
				array("Q4g Capacidad de trabajar autónomamente",
					$si_no['q4g1'], // FI de q4g1
					($si_no['q4g1'] / $submissions), // HI de q4g1
					$si_no['q4g2'],
					($si_no['q4g2'] / $submissions),
					$si_no['q4g3'],
					($si_no['q4g3'] / $submissions),
					$si_no['q4g4'],
					($si_no['q4g4'] / $submissions),
					$si_no['q4g5'],
					($si_no['q4g5'] / $submissions),
					),
				array("Q4h Capacidad de trabajo en equipo",
					$si_no['q4h1'], // FI de q4h1
					($si_no['q4h1'] / $submissions), // HI de q4h1
					$si_no['q4h2'],
					($si_no['q4h2'] / $submissions),
					$si_no['q4h3'],
					($si_no['q4h3'] / $submissions),
					$si_no['q4h4'],
					($si_no['q4h4'] / $submissions),
					$si_no['q4h5'],
					($si_no['q4h5'] / $submissions),
					),
				array("Q4i Creatividad e iniciativa",
					$si_no['q4i1'], // FI de q4i1
					($si_no['q4i1'] / $submissions), // HI de q4i1
					$si_no['q4i2'],
					($si_no['q4i2'] / $submissions),
					$si_no['q4i3'],
					($si_no['q4i3'] / $submissions),
					$si_no['q4i4'],
					($si_no['q4i4'] / $submissions),
					$si_no['q4i5'],
					($si_no['q4i5'] / $submissions),
					),
				array("Q4j Productividad (capacidad de trabajo)",
					$si_no['q4j1'], // FI de q4j1
					($si_no['q4j1'] / $submissions), // HI de q4j1
					$si_no['q4j2'],
					($si_no['q4j2'] / $submissions),
					$si_no['q4j3'],
					($si_no['q4j3'] / $submissions),
					$si_no['q4j4'],
					($si_no['q4j4'] / $submissions),
					$si_no['q4j5'],
					($si_no['q4j5'] / $submissions),
					),
				array("Q4k Responsabilidad",
					$si_no['q4k1'], // FI de q4k1
					($si_no['q4k1'] / $submissions), // HI de q4k1
					$si_no['q4k2'],
					($si_no['q4k2'] / $submissions),
					$si_no['q4k3'],
					($si_no['q4k3'] / $submissions),
					$si_no['q4k4'],
					($si_no['q4k4'] / $submissions),
					$si_no['q4k5'],
					($si_no['q4k5'] / $submissions),
					),
				array("Q4l Manejo de relaciones interpersonales",
					$si_no['q4l1'], // FI de q4l1
					($si_no['q4l1'] / $submissions), // HI de q4l1
					$si_no['q4l2'],
					($si_no['q4l2'] / $submissions),
					$si_no['q4l3'],
					($si_no['q4l3'] / $submissions),
					$si_no['q4l4'],
					($si_no['q4l4'] / $submissions),
					$si_no['q4l5'],
					($si_no['q4l5'] / $submissions),
					),
				array("Q4m Compromiso con la institución o empresa.",
					$si_no['q4m1'], // FI de q4m1
					($si_no['q4m1'] / $submissions), // HI de q4m1
					$si_no['q4m2'],
					($si_no['q4m2'] / $submissions),
					$si_no['q4m3'],
					($si_no['q4m3'] / $submissions),
					$si_no['q4m4'],
					($si_no['q4m4'] / $submissions),
					$si_no['q4m5'],
					($si_no['q4m5'] / $submissions),
					),
				array("Q4n Disposición y habilidad para aplicar normas y procedimientos",
					$si_no['q4n1'], // FI de q4n1
					($si_no['q4n1'] / $submissions), // HI de q4n1
					$si_no['q4n2'],
					($si_no['q4n2'] / $submissions),
					$si_no['q4n3'],
					($si_no['q4n3'] / $submissions),
					$si_no['q4n4'],
					($si_no['q4n4'] / $submissions),
					$si_no['q4n5'],
					($si_no['q4n5'] / $submissions),
					)
  		)
);
  	$dir = file_stream_wrapper_get_instance_by_uri('public://')->realpath();
  	$path = "$dir/$filename";
  	$options = array('format' => 'xls');
  	//array_map('unlink', glob("/home/servilla/public_html/encuestas/sites/default/files/*.xls"));
  	array_map('unlink', glob(variable_get('file_public_path', conf_path() . '/files').'*.xls'));
  	$response = phpexcel_export($headers, $result, $path, $options);
  	if ($response == PHPEXCEL_SUCCESS) {
    	drupal_set_message("We analyzed it! Click the download link at the bottom of this page to download as an MS Excel report");
  	}
  	else {
    	drupal_set_message("Oops ! An error occured !", 'error');
  	}
	  return $page;
	}
}